#!/usr/bin/env python3
"""
catalog — one source for every list of this plugin's skills, and a check that no copy has drifted.

WHY THIS EXISTS
---------------
The skill set was kept by hand in five places (README table, pick-skill, route-hint's name list,
plugin.json's count, marketplace.json's description), and they drifted: marketplace.json said
"Twenty-five" when there were thirty-three. The source of truth is now each SKILL.md's frontmatter:
`name`, `description`, `disable-model-invocation`, and `metadata.stage` / `metadata.card`.

  --write   regenerate CATALOG.md (the short card a fresh session reads) and the skill counts in
            plugin.json, README.md and marketplace.json.
  --check   exit 1 naming every stale or missing copy; run by the unit tests. Also checks that the
            hand-written README table and pick-skill name exactly the skills that exist.

Stdlib only. No YAML library: the frontmatter shape is fixed and tests/test_standalone.py holds it.
"""
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = ROOT / "skills"
CATALOG = ROOT / "CATALOG.md"
PLUGIN_JSON = ROOT / ".claude-plugin" / "plugin.json"
MARKETPLACE_JSON = ROOT / ".claude-plugin" / "marketplace.json"
README = ROOT / "README.md"
PICK_SKILL = SKILLS_DIR / "pick-skill" / "SKILL.md"
PLUGIN = "top-tier-engineer"

# Card order follows the work: get bearings, then the Relay checkpoints, then the entry points
# for broken work, then the skills that run other skills.
STAGES = (
    ("orient", "Orient"), ("frame", "Frame"), ("design", "Design"), ("plan", "Plan"),
    ("build", "Build"), ("prove", "Prove"), ("review", "Review"), ("fix", "Fix"),
    ("ship", "Ship"), ("watch", "Watch"), ("run", "Run it for me"),
)
STAGE_KEYS = {k for k, _ in STAGES}

# Claude Code lists every auto-invocable skill as "- plugin:name: description" inside a budget of 1%
# of the context window in characters (8,000 at 200k tokens), shared by every installed skill. Over
# budget, the least recently used skills lose their description and can no longer trigger by
# themselves (traced in Claude Code 2.1.296). These caps keep this plugin to a fair share of it.
DESC_MAX = 160
LISTING_MAX = 5000

_UNITS = ("zero one two three four five six seven eight nine ten eleven twelve thirteen fourteen "
          "fifteen sixteen seventeen eighteen nineteen").split()
_TENS = "_ _ twenty thirty forty fifty sixty seventy eighty ninety".split()
# "Thirty-three engineering skills", "Twenty-five independent engineering skills"
COUNT_RE = re.compile(r"\b[A-Z][a-z]+(?:-[a-z]+)? ((?:[a-z]+ )?engineering skills)")


def number_word(n):
    if n < 20:
        word = _UNITS[n]
    elif n < 100:
        word = _TENS[n // 10] + ("" if n % 10 == 0 else "-" + _UNITS[n % 10])
    else:
        word = str(n)
    return word[:1].upper() + word[1:]


def read(path):
    return path.read_text(encoding="utf-8").replace("\r\n", "\n")


def frontmatter(text):
    """{'name', 'description', 'manual', 'stage', 'card'} from a SKILL.md, or raise ValueError."""
    if not text.startswith("---\n"):
        raise ValueError("no frontmatter")
    head = text[4:text.index("\n---\n", 4)]
    out = {"manual": False}
    lines = head.split("\n")
    i = 0
    while i < len(lines):
        line = lines[i]
        if line.startswith("name: "):
            out["name"] = line[6:].strip()
        elif line.startswith("description: "):
            value = line[13:].strip()
            if value == ">-":
                i += 1
                value = lines[i].strip()
            out["description"] = value.strip('"')
        elif line == "disable-model-invocation: true":
            out["manual"] = True
        elif line.startswith("  stage: "):
            out["stage"] = line[9:].strip()
        elif line.startswith("  card: "):
            out["card"] = line[8:].strip().strip('"')
        i += 1
    for key in ("name", "description", "stage", "card"):
        if key not in out:
            raise ValueError(f"frontmatter has no {key}")
    if out["stage"] not in STAGE_KEYS:
        raise ValueError(f"unknown stage {out['stage']!r}")
    return out


def load_skills():
    skills = []
    for d in sorted(SKILLS_DIR.iterdir()):
        f = d / "SKILL.md"
        if f.is_file():
            try:
                fm = frontmatter(read(f))
            except ValueError as e:
                raise ValueError(f"skills/{d.name}/SKILL.md: {e}") from None
            fm["dir"] = d.name
            skills.append(fm)
    return skills


def card_text(skills):
    """The card: one line per stage, every skill once, manual-only skills as the slash command."""
    lines = [
        "# Skill card",
        "",
        "<!-- Generated by tools/catalog.py from each SKILL.md's frontmatter. Do not edit. -->",
        "",
        f"{number_word(len(skills))} {PLUGIN} skills, by where the work is. Small changes need none;",
        "for multi-step work, check here first. Load one with the Skill tool by name; a `/command`",
        "is manual-only: suggest it to the user, who types it.",
        "",
    ]
    for key, label in STAGES:
        items = []
        for s in skills:
            if s["stage"] == key:
                ref = f"/{PLUGIN}:{s['name']}" if s["manual"] else s["name"]
                items.append(f"`{ref}` {s['card']}")
        if items:
            lines.append(f"- **{label}:** " + "; ".join(items))
    return "\n".join(lines) + "\n"


def with_count(text, n):
    return COUNT_RE.sub(lambda m: f"{number_word(n)} {m.group(1)}", text, count=1)


def expected_files(skills):
    """{path: expected text} for every generated file."""
    n = len(skills)
    plugin = json.loads(read(PLUGIN_JSON))
    plugin["description"] = with_count(plugin["description"], n)
    market = json.loads(read(MARKETPLACE_JSON))
    for p in market["plugins"]:
        if p["name"] == PLUGIN:
            p["description"] = plugin["description"]
    return {
        CATALOG: card_text(skills),
        PLUGIN_JSON: json.dumps(plugin, indent=2, ensure_ascii=False) + "\n",
        MARKETPLACE_JSON: json.dumps(market, indent=2, ensure_ascii=False) + "\n",
        README: with_count(read(README), n),
    }


def readme_table_names():
    """Skill names in the first column of README's '## The skills' table."""
    section = read(README).split("\n## The skills\n", 1)[-1].split("\n## ", 1)[0]
    return set(re.findall(r"(?m)^\| `([a-z0-9-]+)` \|", section))


def listing_chars(skills):
    """What this plugin's auto-invocable skills cost in the host's skill listing."""
    auto = [s for s in skills if not s["manual"]]
    return sum(len(f"{PLUGIN}:{s['name']}") + 4 + len(s["description"]) for s in auto) + max(0, len(auto) - 1)


def problems(skills):
    found = []
    for s in skills:
        if s["name"] != s["dir"]:
            found.append(f"skills/{s['dir']}: frontmatter name is {s['name']!r}")
        if not s["manual"] and len(s["description"]) > DESC_MAX:
            found.append(f"skills/{s['dir']}: description is {len(s['description'])} chars, cap {DESC_MAX}")
    total = listing_chars(skills)
    if total > LISTING_MAX:
        found.append(f"skill listing is {total} chars, cap {LISTING_MAX}: shorten descriptions")
    for path, text in expected_files(skills).items():
        if not path.exists() or read(path) != text:
            found.append(f"{path.relative_to(ROOT)}: stale, run python tools/catalog.py --write")
    names = {s["name"] for s in skills}
    table = readme_table_names()
    for missing in sorted(names - table):
        found.append(f"README.md: '## The skills' table has no row for {missing}")
    for extra in sorted(table - names):
        found.append(f"README.md: '## The skills' table lists {extra}, which does not exist")
    pick = read(PICK_SKILL)
    for name in sorted(names - {"pick-skill"}):
        if f"`{name}`" not in pick:
            found.append(f"skills/pick-skill/SKILL.md: never names `{name}`")
    return found


def main(argv):
    if len(argv) != 2 or argv[1] not in ("--write", "--check"):
        print(__doc__.strip().split("\n\n")[0])
        print("usage: catalog.py --write | --check")
        return 2
    try:
        skills = load_skills()
    except ValueError as e:
        print(f"catalog: {e}")
        return 1
    if argv[1] == "--write":
        for path, text in expected_files(skills).items():
            if not path.exists() or read(path) != text:
                path.write_text(text, encoding="utf-8", newline="\n")
                print(f"wrote {path.relative_to(ROOT)}")
    found = problems(skills)
    for p in found:
        print(p)
    if not found:
        print(f"catalog: {len(skills)} skills, every copy current, "
              f"listing {listing_chars(skills)}/{LISTING_MAX} chars")
    return 1 if found else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
